apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-ingress-run
spec:
  taskRef:
    name: create-ingress
  inputs:
    params:
    - name: ExternalDomain
      value: {cicdWebhook}
    - name: Service
      value: el-conexp-listener
    - name: ServicePort
      value: "8080"
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
